name: Manual Workflow
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        git remote -v
        git fetch
        git diff --name-only origin/trying origin/master