name: PR File Size Check
on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

env:
  MAX_FILE_SIZE: 1048576 # 1 MB

jobs:
  check_file_size:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Fetch latest changes
        run: git fetch
      - name: Check file size
        run: |
          git fetch
          git diff --name-only origin/${GITHUB_BASE_REF} origin/${GITHUB_HEAD_REF} | while read FILE; do
            if ! git lfs ls-files "$FILE" &> /dev/null && [ $(wc -c < "$FILE") -gt $MAX_FILE_SIZE ]; then
              MAX_FILE_SIZE_MB=$((MAX_FILE_SIZE / 1048576))
              echo "::error file=$FILE::File size exceeds ${MAX_FILE_SIZE_MB} MB limit"
              exit 1
            fi
          done
