name: Always Fails

on:
  push:
  workflow_dispatch:

jobs:
  fail:
    runs-on: ubuntu-latest
    steps:
    - name: Always fail
      run: exit 1
  fail2:
    runs-on: ubuntu-latest
    steps:
    - name: Always fail
      run: |
        for job in ${{ toJson(jobs) }}; do
          echo "$job.name Job Status: ${{ job.status }}"
        done
