name: Send Message Arche Dev
on:
  workflow_dispatch:
  workflow_run:
    workflows: [Always Fails]
    types: [completed]
    branches:
      - master
    
jobs:
  sendMessage:
    runs-on: ubuntu-latest
    steps:
    - name: Always fail
      run: echo  ${{ github.ref_name == 'main' || github.ref_name == 'master' || startsWith( github.ref_name, 'k') }}
