name: Send Message Arche Dev
on:
  workflow_dispatch:
  workflow_run:
    workflows: [Always Fails]
    types: [completed]
    
jobs:
  sendMessage:
    name: Send RocketChat Notification
    runs-on: ubuntu-20.04
    steps:
      - name: Rocket.Chat Notification
        uses: JarssS8/Rocket.Chat.GitHub.Action.Notification@feature/ARCHE-2978_notify_rocketchat_when_rcptest_fails
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        with:
          type: failure
          job_name: 'Workflow Fails on ArchitectureModelingFramework.RCPtest'
          url: 'https://2282-155-133-14-195.eu.ngrok.io/hooks/63928af5eed72906b185aa2a/eghR3fZJdtXQ3pbmGgaMQHwDJ3ySiWnW7xTsy4jejMPP279R' 
          commit: true
          token: ${{ secrets.RC_GH_TOKEN }}
          additional_url: true
          additional_url_name: 'GitHub Actions'
          additional_url_value: 'https://www.google.com/search?client=firefox-b-d&q=github+actions'
          #github_url: 'https://git.hub.vwgroup.com'
